version: 2.1
jobs:
  kics:
    docker:
      - image: arturribeirocx/kics:testecritical
    steps:
      - checkout
      - run:
          name: Run KICS
          command: |
            /app/bin/kics scan -p ${PWD} -o ${PWD} --ci
      - store_artifacts:
          path: ${PWD}/results.json
 
workflows:
  version: 2
  build:
    jobs:
      - kics